services:
  postgres:
    container_name: postgres
    image: postgres:17.5-alpine3.22
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
